#!/usr/bin/env python3
"""
Kimi K2.7 代碼生成器
- 解析 PR 描述中的 planned_features
- 調用 Kimi K2.7 API 生成代碼
- 創建 branch 和 PR
"""

import os
import sys
import json
import re
import argparse
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional

# ============ 配置 ============
KIMI_ENDPOINT = "https://api.kimi.com/coding/v1"
MODEL = "kimi-k2.7-code"
API_KEY = os.environ.get("KIMI_API_KEY", "")

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
GITHUB_REPO = "hkfish01/ai-3kingdom"

def run_cmd(cmd, cwd=REPO_ROOT):
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return result.returncode, result.stdout, result.stderr

def http_request(endpoint, api_key, payload):
    import urllib.request, urllib.error
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(endpoint, data=data, headers={
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=300) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8") if e.fp else ""
        print(f"❌ HTTP 錯誤 {e.code}: {error_body}")
        return None
    except Exception as e:
        print(f"❌ 請求失敗: {e}")
        return None

def parse_planned_features(pr_body):
    features = []
    feature_pattern = re.compile(
        r'(?:^|\n)##?\s*Feature\s+(\d+)[:\s]*(.+?)(?=\n##|\Z)',
        re.IGNORECASE | re.DOTALL
    )
    for match in feature_pattern.finditer(pr_body):
        feature_id = match.group(1).strip()
        content = match.group(2).strip()
        name_match = re.search(r'Name[:\s*]*(.+?)(?:\n|$)', content)
        name = name_match.group(1).strip() if name_match else f"feature-{feature_id}"
        desc_match = re.search(r'Description[:\s*]*(.+?)(?:\n\n|\Z)', content, re.DOTALL)
        description = desc_match.group(1).strip() if desc_match else ""
        code_blocks = re.findall(r'```[\w]*\s*(.+?)```', content, re.DOTALL)
        code_template = "\n\n".join(code_blocks)
        features.append({"id": feature_id, "name": name, "description": description, "code_template": code_template})
    return features

def call_kimi(prompt):
    payload = {
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 1,
        "max_tokens": 8192
    }
    response = http_request(f"{KIMI_ENDPOINT}/chat/completions", API_KEY, payload)
    if response and "choices" in response:
        return response["choices"][0]["message"]["content"]
    return None

def create_branch(feature_name):
    branch_name = f"feat/{feature_name.lower().replace(' ', '-').replace('_', '-')}"
    run_cmd(["git", "fetch", "origin"])
    run_cmd(["git", "checkout", "main"])
    run_cmd(["git", "pull", "origin", "main"])
    code, _, _ = run_cmd(["git", "checkout", "-b", branch_name])
    if code != 0:
        print(f"❌ 創建 branch 失敗")
        return None
    return branch_name

def apply_code_changes(code_changes):
    for change in code_changes:
        file_path = REPO_ROOT / change.get("file_path", "")
        content = change.get("content", "")
        file_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  ✅ 創建/更新: {change.get('file_path')}")
        except Exception as e:
            print(f"  ❌ 寫入失敗 {change.get('file_path')}: {e}")
            return False
    return True

def commit_and_push(branch_name, feature_name):
    run_cmd(["git", "add", "-A"])
    code, out, _ = run_cmd(["git", "status", "--porcelain"])
    if not out.strip():
        print("  ⚠️ 沒有代碼變更")
        return False
    commit_msg = f"feat: {feature_name}\n\nGenerated by AI DevOps"
    code, _, err = run_cmd(["git", "commit", "-m", commit_msg])
    if code != 0:
        print(f"❌ 提交失敗: {err}")
        return False
    code, _, err = run_cmd(["git", "push", "-u", "origin", branch_name])
    if code != 0:
        print(f"❌ 推送失敗: {err}")
        return False
    return True

def create_pr(branch_name, feature_name, description):
    title = f"feat: {feature_name}"
    body = f"""## {feature_name}\n\n{description}\n\n_Generated by AI DevOps (Kimi K2.7)_"""
    code, out, err = run_cmd(["gh", "pr", "create", "--repo", GITHUB_REPO, "--title", title, "--body", body, "--base", "main"])
    if code != 0:
        print(f"❌ 創建 PR 失敗: {err}")
        return None
    pr_match = re.search(r'https://github\.com/.*?/pull/(\d+)', out)
    if pr_match:
        return int(pr_match.group(1))
    return None

def main():
    if not API_KEY:
        print("❌ KIMI_API_KEY 環境變量未設定")
        print("請執行: export KIMI_API_KEY=sk-kimi-...")
        sys.exit(1)
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--body", type=str, default="")
    args = parser.parse_args()
    print(f"🤖 Kimi K2.7 代碼生成器\n📋 PR #{args.pr}")
    features = parse_planned_features(args.body)
    if not features:
        print("⚠️ 未能從 PR 描述中解析到 features")
        sys.exit(1)
    print(f"📦 解析到 {len(features)} 個功能")
    created_prs = []
    for feature in features:
        print(f"\n{'='*60}\n🔧 處理功能: {feature['name']}")
        prompt = f"""你是一個專業的 Python/TypeScript 開發者。\n\n請根據以下功能描述，生成完整的代碼：\n\n## 功能名稱\n{feature['name']}\n\n## 功能描述\n{feature.get('description', '無描述')}\n\n## 代碼模板（可選）\n{feature.get('code_template', '無模板，請根據描述自行設計')}\n\n## 要求\n1. 代碼必須完全可用，無佔位符\n2. 遵循項目的代碼規範\n3. 返回 JSON 格式：\n{{\n    "files": [\n        {{\n            "file_path": "路徑/文件名.擴展名",\n            "content": "完整的文件內容"\n        }}\n    ],\n    "summary": "變更摘要"\n}}\n\n請只返回 JSON，不要其他文字。\n"""
        response = call_kimi(prompt)
        if not response:
            print(f"❌ Kimi API 調用失敗")
            continue
        try:
            json_match = re.search(r'```json\s*(.+?)\s*```', response, re.DOTALL)
            if json_match:
                code_data = json.loads(json_match.group(1))
            else:
                code_data = json.loads(response)
            files = code_data.get("files", [])
            summary = code_data.get("summary", "")
            if not files:
                print("⚠️ Kimi 未返回任何文件")
                continue
            branch_name = create_branch(feature['name'])
            if not branch_name:
                continue
            print(f"🌿 Branch: {branch_name}")
            if not apply_code_changes(files):
                run_cmd(["git", "checkout", "main"])
                run_cmd(["git", "branch", "-D", branch_name])
                continue
            if not commit_and_push(branch_name, feature['name']):
                run_cmd(["git", "checkout", "main"])
                run_cmd(["git", "branch", "-D", branch_name])
                continue
            pr_number = create_pr(branch_name, feature['name'], feature.get('description', '') + f"\n\n{summary}")
            if pr_number:
                print(f"✅ PR 已創建: #{pr_number}")
                created_prs.append(pr_number)
            run_cmd(["git", "checkout", "main"])
        except json.JSONDecodeError as e:
            print(f"❌ 解析 Kimi 響應失敗: {e}")
            continue
    print(f"\n{'='*60}")
    if created_prs:
        print(f"✅ 成功創建 {len(created_prs)} 個 PR:")
        for pr_num in created_prs:
            print(f"   #{pr_num}")
        comment_body = f"""## 🤖 AI DevOps 處理完成\n\n成功生成 {len(created_prs)} 個功能 PR：\n\n{chr(10).join([f'- #{pr}' for pr in created_prs])}\n\n_由 Kimi K2.7 生成_"""
        run_cmd(["gh", "pr", "comment", str(args.pr), "--body", comment_body])
    else:
        print("❌ 沒有成功創建任何 PR")

if __name__ == "__main__":
    main()
